{% set version = "1.5.1" %}

package:
  name: sympy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sympy/sympy-{{ version }}.tar.gz
  sha256: d77901d748287d15281f5ffe5b0fef62dd38f357c2b827c44ff07f35695f4e7e

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - isympy = isympy:main

requirements:
  host:
    - fastcache
    - mpmath
    - pip
    - python
  run:
    - fastcache
    - mpmath >=0.19
    - python
    - gmpy2 >=2.0.8   # [not win]
  run_constrained:
    - antlr-python-runtime >=4.7,<4.8  # [not aarch64 and not ppc64le]

test:
  requires:
    - antlr-python-runtime
  commands:
    - isympy --help
  imports:
    - sympy

about:
  home: https://sympy.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for symbolic mathematics
  description: |
    SymPy is a Python library for symbolic mathematics. It aims to become a
    full-featured computer algebra system (CAS) while keeping the code as
    simple as possible in order to be comprehensible and easily extensible.
  doc_url: https://docs.sympy.org/latest/index.html
  dev_url: https://github.com/sympy/sympy
  doc_source_url: https://github.com/sympy/sympy/tree/master/doc

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - scopatz
